var domains = [
  {
    name: "Conditions",
    subdomains: [{ name: "Health Issue" }, { name: "Health Concern" }],
    prefix: "HC",
    fieldsData: [
      "recordedDate",
      "onset",
      "category",
      "verificationStatus",
      "subject",
      "encounter",
      "asserter",
      "recorder",
      "clinicalStatus",
      "code",
      "abatement",
      "notes",
      "evidence",
      "abatementPartial",
      "internalId",
      "fullDisplay",
      "lastUpdated",
      "createdWhen",
      "objectVersion",
      "summaryDisplay",
      "identifiers",
      "metaTags",
      "securityAndPrivacyTags",
      "id",
    ],
  },
  {
    name: "Allergy Intolerance",
    fieldsData: [
      "narrativeText",
      "recordedDate",
      "onset",
      "category",
      "verificationStatus",
      "patient",
      "encounter",
      "asserter",
      "recorder",
      "clinicalStatus",
      "code",
      "type",
      "criticality",
      "lastOccurrence",
      "reaction",
      "internalId",
      "fullDisplay",
      "lastUpdated",
      "createdWhen",
      "objectVersion",
      "summaryDisplay",
      "identifiers",
      "metaTags",
      "securityAndPrivacyTags",
      "id",
    ],
  },
];
